dist: stable
language: nodejs
node_js: 8
install: npm install

jobs:
  include:
    - stage: test
      script:
        - node index.js
    - stage: deploy
      if: branch = master AND type = push
      env: 
        - script="script/gitinit.sh"
      before_script:
        - chmod +x $script
        - origin="$(./$script)"
      script: 
        - git checkout master
        - git pull origin
        - git push -f $origin HEAD:develop